version: "3"

services:

  mongodb:
    image: mongo:6
    volumes:
      - ./dataset:/dataset

  web:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./dataset:/dataset
    depends_on:
      - mongodb